# Tomcat服务器端口
server:
  port: 8888
#
# Spring组件配置
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3307/coursedesign
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

# Druid后台监控的登录信息
loginAccount:
  username: admin
  password: admin

# Mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Token生成
token:
  SECRET_KEY: nunusedgoodssystem
  EXPIRATION_TIME: 864_000_000

